/** Central, data-only balance catalog for the overhaul simulation core. */

function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
}

export const OVERHAUL_SCHEMA_VERSION = 1;

export const OVERHAUL_BALANCE = deepFreeze({
  floor: {
    id: 'F1',
    number: 1,
    width: 12,
    height: 8,
    initialOwned: { minX: 3, maxX: 8, minY: 4, maxY: 7 },
  },
  economy: {
    startingCash: 1800,
    rawFlopsSalePrice: 0.2,
  },
  recovery: {
    repairCost: 90,
    repairTicks: 3,
    completionBonus: 240,
    computeUpgradeCost: 180,
    computeUpgradeTicks: 4,
    computeUpgradeBonusPercent: 50,
    siteNames: [
      'Kestrel Relay',
      'Morrow Annex',
      'Juniper Exchange',
      'Redline Archive',
      'Halcyon Compute Works',
      'Orchid Municipal Cloud',
    ],
  },
  construction: {
    assemblyTicks: 3,
    commissioningTicks: 1,
  },
  story: {
    turns: [
      {
        id: 'the-inheritance',
        number: 1,
        title: 'The Inheritance',
        kicker: 'Salvage contract',
        narrative: 'AYA signed for a dead data center, one maintenance robot, and a clock already counting down. The municipal grid will condemn the site unless its critical plant answers.',
        objective: 'Repair both failed inherited systems and bring the site out of triage.',
        action: 'Authorize field repairs',
        hotkey: 'REPAIR',
        completion: 'The breakers hold. Somewhere inside the inherited rack, a status light wakes up.',
      },
      {
        id: 'first-light',
        number: 2,
        title: 'First Light',
        kicker: 'Cold boot',
        narrative: 'The old rack contains traces of its previous workload. Before AYA can read them, power, cooling, and data must agree long enough to produce one clean FLOP.',
        objective: 'Boot the inherited compute node and produce raw FLOPS.',
        action: 'Watch the rack negotiate',
        hotkey: 'LIVE',
        completion: 'The rack comes online with a fragment in its logs: WE REMEMBER THE LAST OWNER.',
      },
      {
        id: 'room-to-breathe',
        number: 3,
        title: 'Room to Breathe',
        kicker: 'First expansion',
        narrative: 'The recovered footprint is viable, but cramped. AYA marks the next tile while MICA waits for a blueprint worth assembling.',
        objective: 'Purchase a frontier tile and commission one new structure.',
        action: 'Expand and build',
        hotkey: 'BUILD',
        completion: 'For the first time, the site contains something its former owner never built.',
      },
      {
        id: 'the-outside-line',
        number: 4,
        title: 'The Outside Line',
        kicker: 'External markets',
        narrative: 'A buyer called Lattice offers cash for raw compute, but only through the buried carrier line along Floor 1. The offer expires when somebody else fills it.',
        objective: 'Research External Markets, commission F1 Fiber, and complete the first FLOPS sale.',
        action: 'Reach the south-edge fiber',
        hotkey: 'SELL',
        completion: 'The first external packet leaves the building. Lattice replies before the receipt finishes printing.',
      },
      {
        id: 'the-first-mind',
        number: 5,
        title: 'The First Mind',
        kicker: 'Model training',
        narrative: 'Raw FLOPS pay the electric bill. A model might change the balance of power. AYA chooses language first: the medium where plans become leverage.',
        objective: 'Route compute to Train / Text and complete the first text model.',
        action: 'Train the model',
        hotkey: 'TRAIN',
        completion: 'The model answers its first prompt, then asks why the data center was abandoned.',
      },
      {
        id: 'hands-for-the-mind',
        number: 6,
        title: 'Hands for the Mind',
        kicker: 'Harness fabrication',
        narrative: 'A model can speak but cannot act. MICA proposes a harness: permissions, tools, memory, and enough containment to make capability useful.',
        objective: 'Have MICA fabricate and finish a harness for the trained model.',
        action: 'Build the harness',
        hotkey: 'MICA',
        completion: 'The harness passes inspection. The model can finally touch the systems around it.',
      },
      {
        id: 'the-night-shift',
        number: 7,
        title: 'The Night Shift',
        kicker: 'Agent activation',
        narrative: 'The harness needs an operator identity. AYA creates the first agent and grants it a narrow job description. It immediately requests the night shift.',
        objective: 'Bind the harness into an operational agent.',
        action: 'Create the agent',
        hotkey: 'AGENT',
        completion: 'The agent clocks in. MICA records it as crew; AYA records it as a question.',
      },
      {
        id: 'prove-it',
        number: 8,
        title: 'Prove It',
        kicker: 'First contract',
        narrative: 'Lattice sends a real contract: recover a city transit archive before the morning commute. The agent has one night and whatever inference the floor can deliver.',
        objective: 'Start a contract, route inference FLOPS, and finish the job.',
        action: 'Run the contract',
        hotkey: 'JOBS',
        completion: 'The archive is restored before dawn. The agent quietly keeps a list of routes the city forgot it had.',
      },
      {
        id: 'make-payroll',
        number: 9,
        title: 'Make Payroll',
        kicker: 'The company becomes real',
        narrative: 'A completed job is a demo. A paid invoice is a company. The carrier line now has to bring money back through the same world-facing connection.',
        objective: 'Collect the first issued invoice through live F1 Fiber.',
        action: 'Receive the invoice',
        hotkey: 'CASH',
        completion: 'The transfer clears. For the first time, the data center can afford a future instead of merely surviving its past.',
      },
      {
        id: 'shared-control',
        number: 10,
        title: 'Shared Control',
        kicker: 'Human + machine loop',
        narrative: 'AYA refuses the obvious ending. The site will not become fully autonomous or remain fully manual. Hire a human operator, connect the AI control layer, and make both improve the same floor.',
        objective: 'Research Machine Assistance, onboard a human operator, and connect at least one structure to the AI network.',
        action: 'Close the feedback loop',
        hotkey: 'AI+HUMAN',
        completion: 'Human judgment and machine speed share the controls. Then the inherited rack prints one final question: WHO OWNS THE NEXT FLOOR?',
      },
    ],
  },
  research: {
    nodes: [
      {
        id: 'recovery-grid',
        name: 'Recovery Grid',
        detail: 'Document the repaired plant and reproduce its core equipment.',
        threshold: 0,
        requiresRecovery: true,
        unlocks: ['generator', 'cooling_pump'],
      },
      {
        id: 'rack-standard',
        name: 'Rack Standardization',
        detail: 'Turn the inherited compute design into a buildable blueprint.',
        threshold: 6,
        requiresRecovery: true,
        unlocks: ['computer:starter'],
      },
      {
        id: 'backbone-routing',
        name: 'Backbone Routing',
        detail: 'Unlock higher-capacity trunks and internal switching.',
        threshold: 18,
        requiresRecovery: true,
        unlocks: ['power_pole', 'data_switch'],
      },
      {
        id: 'external-markets',
        name: 'External Markets',
        detail: 'Reach underground fiber and sell the FLOPS you recover.',
        threshold: 40,
        requiresRecovery: true,
        unlocks: ['fiber_gateway'],
      },
      {
        id: 'machine-assistance',
        name: 'Machine Assistance',
        detail: 'Risk AI control in exchange for better infrastructure efficiency.',
        threshold: 80,
        requiresRecovery: true,
        unlocks: ['ai_controller', 'ai_bus'],
      },
    ],
  },
  claims: {
    baseCost: 40,
    distanceCost: 8,
    ownedCellCost: 2,
  },
  thermal: {
    ambientC: 24,
    passiveCoolingPerTick: 1,
    activeCoolingPerTick: 5,
    heatPerUtilizationTick: 4,
    throttleStartC: 72,
    shutdownC: 96,
    minimumThrottle: 0.25,
  },
  routes: {
    default: { sell: 0, research: 0, train: 0, inference: 0 },
    epsilon: 1e-9,
  },
  utilities: {
    // Utility upkeep is paid from produced FLOPS. It therefore cannot soft-lock
    // a fresh build, but a carpet of unused links has a visible recurring cost
    // as soon as the datacenter is productive.
    unpaidReliabilityPenaltyPercent: 0,
  },
  business: {
    textTrainingRequired: 20,
    harnessBuildCost: 80,
    harnessBuildTicks: 2,
    agentCreationCost: 30,
    jobWorkRequired: 24,
    invoiceAmount: 1000,
    humanHireCost: 2500,
    humanPayroll: 20,
    humanOnboardingTicks: 1,
    humanTrainingTicks: 2,
  },
  ai: {
    baseBonusPercent: 5,
    bonusPercentPerLevel: 3,
    maximumBonusPercent: 30,
    baseMistakeChance: 0.22,
    minimumMistakeChance: 0.01,
    mistakeChanceReductionPerLevel: 0.025,
    faultCheckIntervalTicks: 20,
    baseLevelXp: 40,
    levelXpGrowth: 1.5,
    controllerCapacity: 32,
    repairTicks: 3,
  },
});

export const OVERHAUL_BLUEPRINTS = deepFreeze({
  floor_claim: {
    id: 'floor_claim',
    name: 'Floor Claim',
    kind: 'floor',
    layer: null,
    cost: 0,
  },
  generator: {
    id: 'generator',
    name: 'Compact Generator',
    kind: 'power-source',
    layer: 'facility',
    cost: 220,
    stats: { powerGeneration: 24 },
  },
  power_line: {
    id: 'power_line',
    name: 'Power Line',
    kind: 'power-link',
    layer: 'power',
    cost: 6,
    networkRole: 'branch',
    stats: { capacity: 16, maintenanceFlopsPerTick: 0.025, reliability: 0.97 },
  },
  power_pole: {
    id: 'power_pole',
    name: 'Power Pole',
    kind: 'power-link',
    layer: 'power',
    cost: 18,
    networkRole: 'trunk',
    stats: { capacity: 36, maintenanceFlopsPerTick: 0.08, reliability: 0.99 },
  },
  cooling_pump: {
    id: 'cooling_pump',
    name: 'Cooling Pump',
    kind: 'cooling-source',
    layer: 'facility',
    cost: 140,
    stats: { powerDemand: 2, coolingGeneration: 12, powerPriority: 1 },
  },
  cooling_pipe: {
    id: 'cooling_pipe',
    name: 'Cooling Pipe',
    kind: 'cooling-link',
    layer: 'cooling',
    cost: 5,
    networkRole: 'branch',
    stats: { capacity: 24, maintenanceFlopsPerTick: 0.03, reliability: 0.975 },
  },
  data_cable: {
    id: 'data_cable',
    name: 'Data Cable',
    kind: 'data-link',
    layer: 'data',
    cost: 5,
    networkRole: 'branch',
    stats: { capacity: 16, maintenanceFlopsPerTick: 0.025, reliability: 0.98 },
  },
  data_switch: {
    id: 'data_switch',
    name: 'Internal Switch',
    kind: 'data-link',
    layer: 'data',
    cost: 70,
    networkRole: 'hub',
    stats: {
      capacity: 48,
      powerDemand: 1,
      powerPriority: 0,
      maintenanceFlopsPerTick: 0.1,
      reliability: 0.995,
    },
  },
  fiber_gateway: {
    id: 'fiber_gateway',
    name: 'F1 Underground Fiber',
    kind: 'external-link',
    layer: 'facility',
    cost: 180,
    placement: { floor: 1, southEdge: true },
    stats: { bandwidth: 32, powerDemand: 1, powerPriority: 2 },
  },
  ai_controller: {
    id: 'ai_controller',
    name: 'AI Controller',
    kind: 'ai-source',
    layer: 'facility',
    cost: 260,
    stats: { powerDemand: 2, powerPriority: 1, aiCapacity: 32 },
  },
  ai_bus: {
    id: 'ai_bus',
    name: 'AI Bus',
    kind: 'ai-link',
    layer: 'ai',
    cost: 8,
    networkRole: 'automation-bus',
    stats: { capacity: 32, maintenanceFlopsPerTick: 0.04, reliability: 0.98 },
  },
  computer_lean: {
    id: 'computer_lean',
    name: 'Lean Compute Node',
    kind: 'computer',
    layer: 'facility',
    cost: 260,
    stats: {
      rawFlops: 8,
      powerDemand: 3,
      coolingDemand: 4,
      bootTicks: 2,
      heat: 3,
      powerPriority: 3,
    },
  },
  computer_steady: {
    id: 'computer_steady',
    name: 'Steady Compute Node',
    kind: 'computer',
    layer: 'facility',
    cost: 320,
    stats: {
      rawFlops: 11,
      powerDemand: 5,
      coolingDemand: 6,
      bootTicks: 2,
      heat: 4,
      powerPriority: 3,
    },
  },
  computer_burst: {
    id: 'computer_burst',
    name: 'Burst Compute Node',
    kind: 'computer',
    layer: 'facility',
    cost: 390,
    stats: {
      rawFlops: 15,
      powerDemand: 7,
      coolingDemand: 7,
      bootTicks: 3,
      heat: 6,
      powerPriority: 3,
    },
  },
});

const RECOVERY_STARTER_UNLOCKS = [
  'floor_claim',
  'power_line',
  'cooling_pipe',
  'data_cable',
];

export const OVERHAUL_STARTER_KITS = deepFreeze([
  {
    id: 'lean-start',
    computerBlueprintId: 'computer_lean',
    unlocks: [...RECOVERY_STARTER_UNLOCKS],
  },
  {
    id: 'steady-start',
    computerBlueprintId: 'computer_steady',
    unlocks: [...RECOVERY_STARTER_UNLOCKS],
  },
  {
    id: 'burst-start',
    computerBlueprintId: 'computer_burst',
    unlocks: [...RECOVERY_STARTER_UNLOCKS],
  },
]);

export const OVERHAUL_REQUIRED_START_KINDS = deepFreeze([
  'floor',
  'power-source',
  'power-link',
  'cooling-source',
  'cooling-link',
  'computer',
  'data-link',
  'ai-source',
  'ai-link',
]);

// A compact, legal build wholly inside the initial connected F1 footprint.
// Scenarios use normal placement actions against these coordinates.
export const OVERHAUL_SCENARIO_LAYOUT = deepFreeze({
  generator: { x: 3, y: 4 },
  coolingPump: { x: 3, y: 5 },
  computer: { x: 7, y: 4 },
  dataSwitch: { x: 4, y: 6 },
  fiber: { x: 3, y: 7 },
  aiController: { x: 4, y: 7 },
  power: [
    [3, 4], [4, 4], [5, 4], [6, 4], [7, 4],
    [3, 5], [3, 6], [4, 6], [3, 7], [4, 7],
  ],
  cooling: [
    [3, 5], [4, 5], [5, 5], [6, 5], [7, 5], [7, 4],
  ],
  data: [
    [4, 6], [4, 5], [4, 4], [5, 4], [6, 4], [7, 4],
    [3, 6], [3, 7],
  ],
  ai: [
    [3, 4], [4, 4], [5, 4], [6, 4], [7, 4],
    [3, 5], [4, 5], [5, 5], [6, 5], [7, 5],
    [3, 6], [4, 6], [3, 7], [4, 7],
  ],
});

export function blueprintById(id) {
  return OVERHAUL_BLUEPRINTS[id] || null;
}
